name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Angular CLI
        run: npm install -g @angular/cli
      - name: Install Angular CLI ghpages
        run: npm install -g angular-cli-ghpages
      - name: Install dependencies
        run: npm install
      - name: Build and deploy
        run: |
          ng build --base-href="https://jst4rk.github.io/gw-ui/"
          ngh --dir=dist/gw-ui
